import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  vi: {
    // Common
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.export': 'Xuất dữ liệu',
    'common.add': 'Thêm mới',
    'common.edit': 'Chỉnh sửa',
    'common.delete': 'Xóa',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.apply': 'Áp dụng',
    'common.view': 'Xem',
    'common.actions': 'Hành động',
    'common.status': 'Trạng thái',
    'common.date': 'Ngày',
    'common.from': 'Từ',
    'common.to': 'Đến',
    'common.selectDate': 'Chọn ngày',
    'common.name': 'Tên',
    'common.email': 'Email',
    'common.phone': 'Số điện thoại',
    'common.active': 'Hoạt động',
    'common.inactive': 'Không hoạt động',
    'common.all': 'Tất cả',

    // Auth
    'auth.login': 'Đăng nhập',
    'auth.logout': 'Đăng xuất',
    'auth.register': 'Đăng ký',
    'auth.email': 'Email',
    'auth.password': 'Mật khẩu',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.fullName': 'Họ và tên',
    'auth.role': 'Vai trò',
    'auth.rememberMe': 'Ghi nhớ đăng nhập',
    'auth.forgotPassword': 'Quên mật khẩu?',
    'auth.noAccount': 'Chưa có tài khoản?',
    'auth.haveAccount': 'Đã có tài khoản?',

    // Sidebar
    'sidebar.dashboard': 'Trang chủ',
    'sidebar.users': 'Người dùng',
    'sidebar.posts': 'Bài đăng',
    'sidebar.scraper': 'Quét dữ liệu',
    'sidebar.groups': 'Nhóm đã quét',
    'sidebar.products': 'Sản phẩm',
    'sidebar.leads': 'Khách hàng tiềm năng',
    'sidebar.conversations': 'Cuộc trò chuyện',
    'sidebar.reports': 'Báo cáo',
    'sidebar.aiSettings': 'Hệ thống AI',
    'sidebar.sources': 'Kết nối',
    'sidebar.research': 'Nghiên cứu',

    // Admin Dashboard
    'admin.title': 'Trang quản trị',
    'admin.subtitle': 'Tổng quan hệ thống và quản lý',
    'admin.totalUsers': 'Tổng người dùng',
    'admin.activeSessions': 'Phiên hoạt động',
    'admin.apiCalls': 'API Calls hôm nay',
    'admin.systemUptime': 'Thời gian hoạt động',
    'admin.systemHealth': 'Giám sát sức khỏe hệ thống',
    'admin.recentActivities': 'Hoạt động gần đây',
    'admin.manageUsers': 'Quản lý người dùng',
    'admin.databaseBackup': 'Sao lưu dữ liệu',
    'admin.viewLogs': 'Xem nhật ký',
    'admin.analytics': 'Phân tích',

    // Manager Dashboard
    'manager.title': 'Trang quản lý',
    'manager.subtitle': 'Thông tin kinh doanh và quản lý đội nhóm',
    'manager.revenue': 'Doanh thu tháng này',
    'manager.totalLeads': 'Tổng khách hàng tiềm năng',
    'manager.conversionRate': 'Tỷ lệ chuyển đổi',
    'manager.teamMembers': 'Thành viên đội nhóm',
    'manager.teamPerformance': 'Hiệu suất đội nhóm',
    'manager.productTrends': 'Xu hướng sản phẩm',
    'manager.revenueOverview': 'Tổng quan doanh thu',
    'manager.fullReport': 'Báo cáo đầy đủ',
    'manager.thisMonth': 'Tháng này',
    'manager.7days': '7 ngày qua',
    'manager.90days': '90 ngày qua',
    'manager.custom': 'Tùy chỉnh',
    'manager.manageTeam': 'Quản lý đội nhóm',
    'manager.viewAllLeads': 'Xem tất cả khách hàng',
    'manager.reports': 'Báo cáo',
    'manager.setGoals': 'Đặt mục tiêu',

    // Sales Dashboard
    'sales.title': 'Trang bán hàng',
    'sales.subtitle': 'Hoạt động bán hàng và khách hàng tiềm năng hàng ngày',
    'sales.myLeads': 'Khách hàng của tôi',
    'sales.activeChats': 'Cuộc trò chuyện đang hoạt động',
    'sales.callsMade': 'Cuộc gọi đã thực hiện',
    'sales.conversionRate': 'Tỷ lệ chuyển đổi',
    'sales.urgentLeads': 'Khách hàng cần xử lý gấp',
    'sales.urgentLeadsDesc': 'Khách hàng ưu tiên cao cần xử lý ngay lập tức',
    'sales.recentChats': 'Cuộc trò chuyện gần đây',
    'sales.recentChatsDesc': 'Cuộc trò chuyện đang hoạt động',
    'sales.todayTasks': 'Nhiệm vụ hôm nay',
    'sales.todayTasksDesc': 'Lịch trình của bạn hôm nay',
    'sales.table.priority': 'Ưu tiên',
    'sales.table.lead': 'Khách hàng',
    'sales.table.product': 'Sản phẩm',
    'sales.table.budget': 'Ngân sách',
    'sales.table.lastContact': 'Liên hệ cuối',
    'sales.table.status': 'Trạng thái',
    'sales.table.action': 'Hành động',
    'priority.high': 'Cao',
    'priority.medium': 'Trung bình',
    'priority.low': 'Thấp',
    'sales.makeCall': 'Thực hiện cuộc gọi',
    'sales.sendMessage': 'Gửi tin nhắn',
    'sales.addLead': 'Thêm khách hàng',
    'sales.updateStatus': 'Cập nhật trạng thái',
    'sales.myStats': 'Thống kê của tôi',
    'sales.viewAllChats': 'Xem tất cả cuộc trò chuyện',

    // Users Page
    'users.title': 'Quản lý người dùng',
    'users.subtitle': 'Quản lý tài khoản người dùng và phân quyền',
    'users.addUser': 'Thêm người dùng',
    'users.totalUsers': 'Tổng số người dùng',
    'users.activeUsers': 'Người dùng hoạt động',
    'users.newThisMonth': 'Mới trong tháng',
    'users.role': 'Vai trò',
    'users.lastActive': 'Hoạt động lần cuối',
    'users.postsAnalyzed': 'Bài đăng đã phân tích',
    'users.viewDetails': 'Xem chi tiết',

    // Posts Page
    'posts.title': 'Quản lý bài đăng',
    'posts.subtitle': 'Bài đăng từ mạng xã hội đã thu thập và phân tích',
    'posts.totalPosts': 'Tổng bài đăng',
    'posts.buyingDemand': 'Cần mua',
    'posts.sellingDemand': 'Cần bán',
    'posts.filtered': 'Đã lọc',
    'posts.platform': 'Nền tảng',
    'posts.content': 'Nội dung',
    'posts.sentiment': 'Cảm xúc',
    'posts.author': 'Tác giả',
    'posts.type': 'Loại',
    'posts.buying': 'Mua',
    'posts.selling': 'Bán',
    'posts.spam': 'Spam',
    'posts.positive': 'Tích cực',
    'posts.neutral': 'Trung tính',
    'posts.negative': 'Tiêu cực',
    // Posts – extra labels
    'posts.today': 'Hôm nay',
    'posts.noPosts': 'Không có bài đăng',
    'posts.noPostsHint': 'Bài đăng sẽ hiển thị ở đây sau khi quét từ trang \"Quét dữ liệu\"',
    'posts.refresh': 'Làm mới',
    'posts.table.content': 'Nội dung',
    'posts.table.type': 'Loại',
    'posts.table.category': 'Danh mục',
    'posts.table.platform': 'Nền tảng',
    'posts.table.author': 'Tác giả',
    'posts.table.price': 'Giá',
    'posts.table.confidence': 'Độ tin cậy',
    'posts.table.time': 'Thời gian',
    'posts.table.actions': 'Hành động',
    'posts.viewOriginal': 'Xem bài gốc',
    'posts.pagination.prev': 'Trước',
    'posts.pagination.next': 'Sau',

    // Products Page
    'products.title': 'Quản lý sản phẩm',
    'products.subtitle': 'Theo dõi giá và nhu cầu thị trường',
    'products.addProduct': 'Thêm sản phẩm',
    'products.addTrackedProduct': 'Thêm sản phẩm theo dõi',
    'products.totalProducts': 'Tổng sản phẩm',
    'products.highDemand': 'Nhu cầu cao',
    'products.totalBuyingPosts': 'Tổng bài mua',
    'products.totalSellingPosts': 'Tổng bài bán',
    'products.avgPrice': 'Giá trung bình',
    'products.minPrice': 'Giá thấp nhất',
    'products.maxPrice': 'Giá cao nhất',
    'products.priceRange': 'Khoảng giá',
    'products.product': 'Sản phẩm',
    'products.category': 'Danh mục',
    'products.price': 'Giá',
    'products.demand': 'Nhu cầu',
    'products.mentions': 'Đề cập',
    'products.trend': 'Xu hướng',
    'products.high': 'Cao',
    'products.medium': 'Trung bình',
    'products.low': 'Thấp',
    'products.trending': 'Đang tăng',
    'products.stable': 'Ổn định',
    'products.declining': 'Giảm',
    'products.listTitle': 'Danh sách sản phẩm',
    'products.searchPlaceholder': 'Tìm kiếm sản phẩm...',
    'products.editProduct': 'Chỉnh sửa sản phẩm',

    // Leads Page
    'leads.title': 'Quản lý khách hàng tiềm năng',
    'leads.subtitle': 'Theo dõi và quản lý khách hàng tiềm năng',
    'leads.addLead': 'Thêm khách hàng',
    'leads.totalLeads': 'Tổng khách hàng',
    'leads.hot': 'Nóng',
    'leads.contacted': 'Đã liên hệ',
    'leads.converted': 'Đã chuyển đổi',
    'leads.lead': 'Khách hàng',
    'leads.contact': 'Liên hệ',
    'leads.interest': 'Quan tâm',
    'leads.source': 'Nguồn',
    'leads.assignedTo': 'Phân công cho',
    'leads.priority': 'Ưu tiên',
    'leads.new': 'Mới',
    'leads.inProgress': 'Đang xử lý',
    'leads.closed': 'Đã đóng',
    // Leads – extra labels
    'leads.highPotential': 'Tiềm năng cao',
    'leads.table.priority': 'Ưu tiên',
    'leads.table.lead': 'Khách hàng',
    'leads.table.contact': 'Liên hệ',
    'leads.table.interest': 'Quan tâm',
    'leads.table.type': 'Loại',
    'leads.table.budget': 'Ngân sách',
    'leads.table.status': 'Trạng thái',
    'leads.table.source': 'Nguồn',
    'leads.table.notes': 'Ghi chú',
    'leads.table.actions': 'Hành động',
    'leads.filter.placeholder': 'Tìm kiếm...',
    'leads.status.new': 'Mới',
    'leads.status.potential': 'Tiềm năng',
    'leads.status.ready': 'Sẵn sàng mua',
    'leads.status.purchased': 'Đã mua',
    'leads.status.contacted': 'Đã liên hệ',
    'leads.status.qualified': 'Tiềm năng',
    'leads.status.lost': 'Thất bại',

    // Sales Log
    'sidebar.salesLog': 'Nhật ký Sales',
    'salesLog.title': 'Nhật ký Sales',
    'salesLog.subtitle': 'Theo dõi lịch sử chăm sóc khách hàng',
    'salesLog.totalLogs': 'Tổng nhật ký',
    'salesLog.caretaker': 'Người chăm sóc',
    'salesLog.editTime': 'Ngày giờ chỉnh sửa',
    'salesLog.customerRequest': 'Đề xuất của khách hàng',
    'salesLog.conclusion': 'Kết luận',
    'salesLog.adminResponse': 'Phản hồi Admin',
    'salesLog.pending': 'Chờ duyệt',
    'salesLog.approved': 'Đã duyệt - Bán',
    'salesLog.rejected': 'Đã duyệt - Không bán',
    'salesLog.noLogs': 'Chưa có nhật ký nào',
    'salesLog.customer': 'Khách hàng',
    'salesLog.approve': 'Duyệt',
    'salesLog.reject': 'Từ chối',
    'salesLog.reviewDialogTitle': 'Duyệt nhật ký Sales',
    'salesLog.reviewDialogDesc': 'Xác nhận duyệt hoặc từ chối nhật ký này',
    'salesLog.approveSuccess': 'Đã duyệt thành công',
    'salesLog.rejectSuccess': 'Đã từ chối',
    'salesLog.searchPlaceholder': 'Tìm kiếm...',
    'salesLog.reviewCustomer': 'Khách hàng',
    'salesLog.reviewCaretaker': 'Người chăm sóc',
    'salesLog.reviewRequest': 'Đề xuất',
    'salesLog.reviewConclusion': 'Kết luận',
    'salesLog.reviewAdminResponse': 'Phản hồi của Admin',
    'salesLog.reviewAdminResponsePlaceholder': 'Nhập phản hồi...',

    // Conversations Page
    'conversations.title': 'Cuộc trò chuyện',
    'conversations.subtitle': 'Quản lý tin nhắn và tương tác với khách hàng',
    'conversations.totalChats': 'Tổng cuộc trò chuyện',
    'conversations.unread': 'Chưa đọc',
    'conversations.avgResponse': 'Phản hồi TB',
    'conversations.satisfaction': 'Hài lòng',
    'conversations.selectChat': 'Chọn cuộc trò chuyện để xem chi tiết',
    'conversations.typeMessage': 'Nhập tin nhắn...',
    'conversations.send': 'Gửi',

    // Reports Page
    'reports.title': 'Báo cáo và phân tích',
    'reports.subtitle': 'Tổng quan hiệu suất và xu hướng',
    'reports.generateReport': 'Tạo báo cáo',
    'reports.totalRevenue': 'Tổng doanh thu',
    'reports.newLeads': 'Khách hàng mới',
    'reports.conversionRate': 'Tỷ lệ chuyển đổi',
    'reports.customerSatisfaction': 'Sự hài lòng khách hàng',
    'reports.performanceOverview': 'Tổng quan hiệu suất',
    'reports.topProducts': 'Sản phẩm hàng đầu',
    // Reports – UI texts
    'reports.totalPosts': 'Tổng bài đăng',
    'reports.buyingPosts': 'Bài mua',
    'reports.sellingPosts': 'Bài bán',
    'reports.avgConfidence': 'Độ chính xác TB',
    'reports.categoryDistributionTitle': 'Phân bố theo danh mục',
    'reports.categoryDistributionDesc': 'Top danh mục sản phẩm được quan tâm',
    'reports.locationDistributionTitle': 'Phân bố theo địa điểm',
    'reports.locationDistributionDesc': 'Khu vực có nhu cầu cao',
    'reports.avgPriceTrendTitle': 'Xu hướng giá trung bình',
    'reports.buySellRatioTitle': 'Tỷ lệ mua/bán',
    'reports.avgResponseTimeTitle': 'Thời gian phản hồi TB',
    'reports.range7days': '7 ngày qua',
    'reports.range30days': '30 ngày qua',
    'reports.range90days': '90 ngày qua',
    'reports.rangeCustom': 'Tùy chỉnh',
    'reports.pickDate': 'Chọn ngày',
    'reports.exportFormatExcel': 'Excel',
    'reports.exportFormatCsv': 'CSV',
    'reports.exportButton': 'Xuất báo cáo',
    'reports.exportSuccess': 'Báo cáo đã được xuất thành công',
    'reports.exportError': 'Lỗi khi xuất báo cáo',

    // AI Settings Page
    'ai.title': 'Cài đặt hệ thống AI',
    'ai.subtitle': 'Cấu hình và quản lý các mô hình AI',
    'ai.models': 'Mô hình AI',
    'ai.nlpModel': 'Mô hình NLP',
    'ai.ocrModel': 'Mô hình OCR',
    'ai.spamDetector': 'Phát hiện Spam',
    'ai.priceExtractor': 'Trích xuất giá',
    'ai.confidence': 'Độ tin cậy',
    'ai.accuracy': 'Độ chính xác',
    'ai.performance': 'Hiệu suất',
    'ai.configure': 'Cấu hình',
    'ai.retrain': 'Huấn luyện lại',

    // Sources Page
    'sources.title': 'Kết nối nguồn dữ liệu',
    'sources.subtitle': 'Quản lý kết nối mạng xã hội và thu thập dữ liệu',
    'sources.addSource': 'Thêm nguồn mới',
    'sources.source': 'Nguồn',
    'sources.connected': 'Đã kết nối',
    'sources.postsCollected': 'Bài đăng thu thập',
    'sources.lastSync': 'Đồng bộ lần cuối',
    'sources.syncNow': 'Đồng bộ ngay',
    'sources.disconnect': 'Ngắt kết nối',

    // Groups Page
    'groups.title': 'Quản lý nhóm Facebook',
    'groups.subtitle': 'Danh sách các nhóm đã quét và thêm thủ công',
    'groups.totalGroups': 'Tổng số nhóm',
    'groups.searchPlaceholder': 'Tìm theo tên, URL hoặc địa điểm...',
    'groups.name': 'Tên nhóm',
    'groups.url': 'URL nhóm',
    'groups.location': 'Địa điểm',
    'groups.keywords': 'Từ khóa',
    'groups.addGroup': 'Thêm nhóm thủ công',
    'groups.fetchName': 'Lấy tên nhóm tự động',
    'groups.deleteConfirm': 'Bạn có chắc muốn xóa nhóm này?',

    // Scraper Page
    'scraper.subtitle': 'Thu thập dữ liệu từ Facebook Groups và Marketplace',
    'scraper.step1Title': 'Bước 1: Đăng nhập Facebook',
    'scraper.step1Desc': 'Đăng nhập để lưu cookie và sử dụng cho việc quét dữ liệu',
    'scraper.emailLabel': 'Email Facebook',
    'scraper.loginButton': 'Đăng nhập & Lưu Cookie',
    'scraper.modeTitle': 'Chọn chế độ quét',
    'scraper.searchModeTitle': 'Search Mode',
    'scraper.searchModeDesc': 'Tìm theo từ khóa',
    'scraper.feedModeTitle': 'Feed Mode',
    'scraper.feedModeDesc': 'Cào feed + lọc',
    'scraper.step2SearchTitle': 'Bước 2: Quét theo Search',
    'scraper.step2SearchDesc': 'Nhập link Group/Marketplace và từ khóa để tìm kiếm',
    'scraper.groupLinkLabel': 'Link Group hoặc Marketplace',
    'scraper.keywordsLabel': 'Từ khóa (mỗi dòng 1 từ khóa)',
    'scraper.searchButtonIdle': '🔍 Quét Search',
    'scraper.searchButtonLoading': 'Đang quét Search...',
    'scraper.step2FeedTitle': 'Bước 2: Cào Feed',
    'scraper.feedLinkLabel': 'Link Feed',
    'scraper.scrollLabel': 'Số lần cuộn trang',
    'scraper.scrollMin': '5 (Nhanh)',
    'scraper.scrollMax': '30 (Nhiều)',
    'scraper.step2FeedDesc': 'Vào trang feed và cuộn để load tất cả bài viết, AI sẽ tự động phân loại',
    'scraper.serverOnline': 'Server Online',
    'scraper.serverOffline': 'Server Offline',
    'scraper.serverChecking': 'Đang kiểm tra...',
    'scraper.offlineTitle': 'Backend server không hoạt động',
    'scraper.offlineDesc': 'Hãy chạy backend server trước khi sử dụng tính năng này:',
    'scraper.feedButtonIdle': '🚀 Quét Feed',
    'scraper.feedButtonLoading': 'Đang quét Feed...',
    // Research Page
    'research.title': 'Nghiên cứu thị trường',
    'research.subtitle': 'Phân tích xu hướng và insights thị trường',
    'research.startResearch': 'Bắt đầu nghiên cứu',
    'research.marketTrends': 'Xu hướng thị trường',
    'research.keywords': 'Từ khóa',
    'research.insights': 'Insights',

    // Roles
    'role.admin': 'Quản trị viên',
    'role.manager': 'Store Manager',
    'role.sales': 'Sales Staff',
    'role.smb': 'SMB Owner',
    'role.student': 'IT Student',

    // Account
    'account.button': 'Tài khoản',
    'account.title': 'Quản lý tài khoản',
    'account.subtitle': 'Xem và chỉnh sửa thông tin tài khoản của bạn',
    'account.profileTab': 'Thông tin cá nhân',
    'account.passwordTab': 'Đổi mật khẩu',
    'account.createdAt': 'Ngày tạo',
    'account.unknown': 'Không xác định',
    'account.enterName': 'Nhập họ và tên',
    'account.emailCannotChange': 'Email không thể thay đổi',
    'account.currentPassword': 'Mật khẩu hiện tại',
    'account.newPassword': 'Mật khẩu mới',
    'account.enterCurrentPassword': 'Nhập mật khẩu hiện tại',
    'account.enterNewPassword': 'Nhập mật khẩu mới',
    'account.confirmNewPassword': 'Xác nhận mật khẩu mới',
    'account.changePassword': 'Đổi mật khẩu',
    'account.saving': 'Đang lưu...',
    'account.updateSuccess': 'Cập nhật thông tin thành công',
    'account.updateFailed': 'Cập nhật thông tin thất bại',
    'account.changePasswordSuccess': 'Đổi mật khẩu thành công',
    'account.changePasswordFailed': 'Đổi mật khẩu thất bại',
    'account.fillAllFields': 'Vui lòng điền đầy đủ thông tin',
    'account.passwordMismatch': 'Mật khẩu xác nhận không khớp',
    'account.passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
    'account.enterPhone': 'Nhập số điện thoại',
    'account.company': 'Công ty / Tổ chức',
    'account.enterCompany': 'Nhập tên công ty hoặc tổ chức',
    'account.location': 'Địa chỉ',
    'account.enterLocation': 'Nhập địa chỉ của bạn',

    // Login Page
    'login.welcomeBack': 'Chào mừng trở lại!',
    'login.systemDesc': 'Hệ thống AI phân tích nhu cầu mua bán trên mạng xã hội',
    'login.aiAnalysis': 'Phân tích AI thông minh',
    'login.aiAccuracy': 'Độ chính xác lên đến 94.2%',
    'login.autoCollect': 'Tự động thu thập dữ liệu',
    'login.platformList': 'Từ Facebook, Instagram, Twitter',
    'login.detailedReports': 'Báo cáo chi tiết',
    'login.marketTrends': 'Phân tích xu hướng thị trường',
    'login.title': 'Đăng nhập',
    'login.subtitle': 'Nhập thông tin tài khoản để tiếp tục',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.loggingIn': 'Đang đăng nhập...',
    'login.loginButton': 'Đăng nhập',
    'login.orDemoAccount': 'Hoặc dùng tài khoản demo',
    'login.noAccount': 'Chưa có tài khoản?',
    'login.registerNow': 'Đăng ký ngay',
    'login.forgotTitle': 'Quên mật khẩu',
    'login.forgotDesc': 'Nhập email của bạn để nhận mã xác nhận (OTP) đặt lại mật khẩu.',
    'login.enterEmail': 'Vui lòng nhập email',
    'login.sendingCode': 'Đang gửi mã xác nhận...',
    'login.codeSent': 'Nếu email tồn tại, mã xác nhận đã được gửi. Vui lòng kiểm tra hộp thư.',
    'login.errorSendCode': 'Lỗi khi gửi mã xác nhận',
    'login.cancel': 'Hủy',
    'login.sendCode': 'Gửi mã',
    'login.sending': 'Đang gửi...',
    'login.step2Desc': 'Nhập mã xác nhận đã được gửi đến email của bạn và đặt mật khẩu mới.',
    'login.otpLabel': 'Mã xác nhận (OTP)',
    'login.otpPlaceholder': 'Nhập mã 6 số',
    'login.newPassword': 'Mật khẩu mới',
    'login.confirmNewPassword': 'Xác nhận mật khẩu mới',
    'login.back': 'Quay lại',
    'login.resendCode': 'Gửi lại mã',
    'login.resendingCode': 'Đang gửi lại mã xác nhận...',
    'login.codeResent': 'Nếu email tồn tại, mã xác nhận mới đã được gửi. Vui lòng kiểm tra hộp thư.',
    'login.errorResendCode': 'Lỗi khi gửi lại mã xác nhận',
    'login.fillAllFields': 'Vui lòng nhập đầy đủ thông tin',
    'login.changingPassword': 'Đang đổi mật khẩu...',
    'login.changePassword': 'Đổi mật khẩu',
    'login.passwordChanged': 'Đổi mật khẩu thành công',
    'login.passwordChangeFailed': 'Đổi mật khẩu thất bại',
    'login.processing': 'Đang xử lý...',
    'login.enterEmailFirst': 'Vui lòng nhập email để gửi lại mã',

    // Register Page
    'register.startFree': 'Bắt đầu miễn phí ngay hôm nay',
    'register.createDesc': 'Tạo tài khoản và trải nghiệm sức mạnh của AI trong phân tích mạng xã hội',
    'register.freeTrial': 'Dùng thử 30 ngày miễn phí',
    'register.noCard': 'Không cần thẻ tín dụng',
    'register.setup5min': 'Thiết lập trong 5 phút',
    'register.easyFast': 'Dễ dàng và nhanh chóng',
    'register.support247': 'Hỗ trợ 24/7',
    'register.supportDesc': 'Đội ngũ chăm sóc khách hàng luôn sẵn sàng',
    'register.haveAccount': 'Đã có tài khoản?',
    'register.loginNow': 'Đăng nhập ngay',
    'register.createAccount': 'Tạo tài khoản',
    'register.fillInfo': 'Điền thông tin để bắt đầu sử dụng hệ thống',
    'register.fullName': 'Họ và tên',
    'register.namePlaceholder': 'Nguyễn Văn A',
    'register.phone': 'Số điện thoại',
    'register.phonePlaceholder': '0912345678',
    'register.phoneAvailable': 'Số điện thoại có thể sử dụng',
    'register.phoneTaken': 'Số điện thoại này đã được đăng ký',
    'register.emailAvailable': 'Email có thể sử dụng',
    'register.emailTaken': 'Email này đã được đăng ký',
    'register.otpLabel': 'Mã xác nhận',
    'register.otpPlaceholder': 'Nhập mã 6 số đã gửi về email',
    'register.sendOtp': 'Gửi mã',
    'register.sendingOtp': 'Đang gửi...',
    'register.otpSending': 'Đang gửi mã xác nhận...',
    'register.otpSent': 'Mã xác nhận đăng ký đã được gửi. Vui lòng kiểm tra hộp thư (bao gồm cả mục Spam).',
    'register.otpError': 'Không thể gửi mã xác nhận. Vui lòng thử lại.',
    'register.enterEmailFirst': 'Vui lòng nhập email trước khi gửi mã',
    'register.company': 'Công ty',
    'register.companyPlaceholder': 'Tên công ty',
    'register.location': 'Địa điểm',
    'register.locationPlaceholder': 'Hà Nội',
    'register.role': 'Vai trò',
    'register.rolePlaceholder': 'Chọn vai trò của bạn',
    'register.roleSMB': 'SMB Owner - Chủ cửa hàng nhỏ',
    'register.roleSales': 'Sales Staff - Nhân viên bán hàng',
    'register.roleManager': 'Store Manager - Quản lý cửa hàng',
    'register.roleStudent': 'IT Student - Sinh viên IT',
    'register.password': 'Mật khẩu',
    'register.confirmPassword': 'Xác nhận mật khẩu',
    'register.agreeTerms': 'Tôi đồng ý với',
    'register.termsOfUse': 'Điều khoản sử dụng',
    'register.and': 'và',
    'register.privacyPolicy': 'Chính sách bảo mật',
    'register.createButton': 'Tạo tài khoản',
    'register.consentText': 'Bằng cách đăng ký, bạn đồng ý nhận email về sản phẩm, cập nhật và khuyến mãi.',
    'register.validation.fullName': 'Vui lòng nhập họ tên',
    'register.validation.email': 'Vui lòng nhập email',
    'register.validation.emailInvalid': 'Email không hợp lệ',
    'register.validation.phone': 'Vui lòng nhập số điện thoại',
    'register.validation.phoneInvalid': 'Số điện thoại không hợp lệ',
    'register.validation.role': 'Vui lòng chọn vai trò',
    'register.validation.password': 'Vui lòng nhập mật khẩu',
    'register.validation.passwordMin': 'Mật khẩu phải có ít nhất 6 ký tự',
    'register.validation.passwordMismatch': 'Mật khẩu không khớp',
    'register.validation.otp': 'Vui lòng nhập mã xác nhận đã gửi về email',
    'register.validation.terms': 'Vui lòng đồng ý với điều khoản',

    // AI Settings Page
    'aiSettings.title': 'Cài đặt AI',
    'aiSettings.subtitle': 'Cấu hình mô hình AI và các tham số phân tích',
    'aiSettings.modelConfig': 'Cấu hình mô hình AI',
    'aiSettings.modelConfigDesc': 'Quản lý các module AI và cài đặt của chúng',
    'aiSettings.nlpModel': 'Phân loại văn bản NLP',
    'aiSettings.nlpDesc': 'Phân loại bài đăng là yêu cầu mua hoặc bán',
    'aiSettings.ocrModel': 'Đọc hình ảnh OCR',
    'aiSettings.ocrDesc': 'Trích xuất văn bản từ hình ảnh trong bài đăng',
    'aiSettings.spamDetector': 'Phát hiện Spam',
    'aiSettings.spamDesc': 'Lọc bài đăng spam và lừa đảo',
    'aiSettings.priceExtractor': 'Trích xuất giá',
    'aiSettings.priceDesc': 'Xác định và trích xuất thông tin giá',
    'aiSettings.accuracy': 'Độ chính xác',
    'aiSettings.advancedSettings': 'Cài đặt nâng cao',
    'aiSettings.advancedDesc': 'Tinh chỉnh các tham số phân tích AI',
    'aiSettings.confidenceThreshold': 'Ngưỡng độ tin cậy',
    'aiSettings.confidenceHint': 'Chỉ hiển thị kết quả có mức độ tin cậy trên ngưỡng này',
    'aiSettings.modelVersion': 'Phiên bản mô hình',
    'aiSettings.versionStable': 'Ổn định',
    'aiSettings.versionProduction': 'Production',
    'aiSettings.versionLatest': 'Mới nhất',
    'aiSettings.versionBeta': 'Beta',
    'aiSettings.versionHint': 'Chọn phiên bản mô hình AI để sử dụng cho phân tích',
    'aiSettings.saveConfig': 'Lưu cấu hình',
    'aiSettings.resetDefault': 'Đặt lại mặc định',
    'aiSettings.performance': 'Hiệu suất mô hình',
    'aiSettings.performanceDesc': 'Các chỉ số hiệu suất thời gian thực',
    'aiSettings.overallAccuracy': 'Độ chính xác tổng thể',
    'aiSettings.processingSpeed': 'Tốc độ xử lý',
    'aiSettings.avgPerPost': 'trung bình/bài',
    'aiSettings.activeModels': 'Mô hình hoạt động',
    'aiSettings.quickActions': 'Thao tác nhanh',
    'aiSettings.testModel': 'Kiểm tra mô hình',
    'aiSettings.calibrate': 'Hiệu chỉnh mô hình',
    'aiSettings.viewTrainingData': 'Xem dữ liệu huấn luyện',

    // Scraper Page - Additional
    'scraper.enterFbEmail': 'Vui lòng nhập email Facebook',
    'scraper.openingChrome': 'Đang mở Chrome để đăng nhập...',
    'scraper.loginSuccess': 'Đăng nhập thành công!',
    'scraper.loginError': 'Lỗi đăng nhập',
    'scraper.cannotConnectScraper': 'Không thể kết nối đến scraper server',
    'scraper.checkServer': 'Hãy kiểm tra server đang chạy.',
    'scraper.fillAllInfo': 'Vui lòng điền đầy đủ thông tin',
    'scraper.scrapingAI': 'Đang quét dữ liệu và phân tích với AI...',
    'scraper.foundPosts': 'Tìm thấy {count} bài viết!',
    'scraper.savedInfo': 'Đã lưu: {posts} bài đăng, {leads} khách hàng tiềm năng',
    'scraper.errorScraping': 'Lỗi khi quét dữ liệu',
    'scraper.cannotConnect': 'Không thể kết nối đến server',
    'scraper.enterEmailKeywords': 'Vui lòng nhập email và từ khóa',
    'scraper.scanningGroups': 'Đang quét danh sách hội nhóm liên quan tới từ khóa...',
    'scraper.foundGroups': 'Tìm thấy {count} hội nhóm liên quan tới từ khóa',
    'scraper.errorGroups': 'Lỗi khi quét danh sách hội nhóm',
    'scraper.cannotConnectGroups': 'Không thể kết nối đến server (quét hội nhóm)',
    'scraper.fillEmailFeed': 'Vui lòng điền đầy đủ thông tin (email và link feed)',
    'scraper.scrapingFeeds': 'Đang quét {count} feed với mức độ ưu tiên {priority}...',
    'scraper.priorityHigh': 'Cao',
    'scraper.priorityMedium': 'Trung bình',
    'scraper.priorityLow': 'Thấp',
    'scraper.foundPostsFromGroups': 'Tìm thấy {posts} bài viết từ {groups} nhóm!',
    'scraper.location': 'Địa điểm (tùy chọn)',
    'scraper.locationPlaceholder': 'VD: Hà Nội, TP.HCM, Đà Nẵng...',
    'scraper.locationHint': 'Nếu nhập địa điểm, hệ thống sẽ ưu tiên tìm các nhóm liên quan tới khu vực đó.',
    'scraper.scanning': 'Đang quét...',
    'scraper.scanGroupsBtn': 'Quét danh sách hội nhóm theo từ khóa',
    'scraper.feedLabel': 'Link nhóm Facebook (hoặc chọn từ danh sách đã quét)',
    'scraper.feedPlaceholder': 'https://www.facebook.com/groups/123456789\n(Mỗi link 1 dòng)',
    'scraper.selectFromScraped': 'Chọn từ nhóm đã quét',
    'scraper.clear': 'Xóa',
    'scraper.selectedGroups': 'Đã chọn {count} nhóm',
    'scraper.priorityLabel': 'Mức độ ưu tiên quét',
    'scraper.priorityHighDesc': 'Cao - Quét kỹ, nhiều bài hơn',
    'scraper.priorityMediumDesc': 'Trung bình - Cân bằng',
    'scraper.priorityLowDesc': 'Thấp - Nhanh, ít bài hơn',
    'scraper.enterLinkWarning': 'Vui lòng nhập link nhóm hoặc chọn từ danh sách đã quét',
    'scraper.groupListTitle': 'Danh sách hội nhóm liên quan tới từ khóa',
    'scraper.keywords': 'Từ khóa',
    'scraper.openGroup': 'Mở nhóm',
    'scraper.results': 'Kết quả',
    'scraper.autoSaved': 'đã tự động lưu',
    'scraper.buy': 'Mua',
    'scraper.sell': 'Bán',
    'scraper.other': 'Khác',
    'scraper.confidence': 'tin cậy',

    // Sales Dashboard
    'sales.title': 'Bảng điều khiển Sales',
    'sales.subtitle': 'Quản lý leads và hoạt động bán hàng của bạn',
    'sales.myLeads': 'Leads của tôi',
    'sales.activeChats': 'Cuộc trò chuyện',
    'sales.callsMade': 'Cuộc gọi',
    'sales.conversionRate': 'Tỷ lệ chuyển đổi',
    'sales.viewAllChats': 'Xem tất cả chat',
    'sales.urgentLeads': 'Leads cần xử lý gấp',
    'sales.urgentLeadsDesc': 'Các khách hàng tiềm năng có độ ưu tiên cao',
    'sales.recentChats': 'Tin nhắn gần đây',
    'sales.recentChatsDesc': 'Các cuộc trò chuyện mới nhất',
    'sales.todayTasks': 'Nhiệm vụ hôm nay',
    'sales.todayTasksDesc': 'Lịch làm việc của bạn',
    'sales.makeCall': 'Gọi điện',
    'sales.sendMessage': 'Nhắn tin',
    'sales.addLead': 'Thêm Lead',
    'sales.updateStatus': 'Cập nhật',
    'sales.myStats': 'Thống kê',
    'sales.table.priority': 'Ưu tiên',
    'sales.table.lead': 'Khách hàng',
    'sales.table.product': 'Sản phẩm',
    'sales.table.budget': 'Ngân sách',
    'sales.table.lastContact': 'Liên hệ cuối',
    'sales.table.status': 'Trạng thái',
    'sales.table.action': 'Hành động',
    'sales.today': 'hôm nay',
    'sales.unread': 'chưa đọc',

    // Priority
    'priority.high': 'Cao',
    'priority.medium': 'Trung bình',
    'priority.low': 'Thấp',
  },
  en: {
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.add': 'Add New',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.apply': 'Apply',
    'common.view': 'View',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.from': 'From',
    'common.to': 'To',
    'common.selectDate': 'Select date',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.all': 'All',

    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.role': 'Role',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',

    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.users': 'Users',
    'sidebar.posts': 'Posts',
    'sidebar.scraper': 'Data Scraper',
    'sidebar.groups': 'Groups',
    'sidebar.products': 'Products',
    'sidebar.leads': 'Leads',
    'sidebar.conversations': 'Conversations',
    'sidebar.reports': 'Reports',
    'sidebar.aiSettings': 'AI System',
    'sidebar.sources': 'Connections',
    'sidebar.research': 'Research',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'System overview and management',
    'admin.totalUsers': 'Total Users',
    'admin.activeSessions': 'Active Sessions',
    'admin.apiCalls': 'API Calls Today',
    'admin.systemUptime': 'System Uptime',
    'admin.systemHealth': 'System Health Monitor',
    'admin.recentActivities': 'Recent Activities',
    'admin.manageUsers': 'Manage Users',
    'admin.databaseBackup': 'Database Backup',
    'admin.viewLogs': 'View Logs',
    'admin.analytics': 'Analytics',

    // Manager Dashboard
    'manager.title': 'Manager Dashboard',
    'manager.subtitle': 'Business insights and team management',
    'manager.revenue': 'Revenue This Month',
    'manager.totalLeads': 'Total Leads',
    'manager.conversionRate': 'Conversion Rate',
    'manager.teamMembers': 'Team Members',
    'manager.teamPerformance': 'Team Performance',
    'manager.productTrends': 'Product Trends',
    'manager.revenueOverview': 'Revenue Overview',
    'manager.fullReport': 'Full Report',
    'manager.thisMonth': 'This Month',
    'manager.7days': 'Last 7 days',
    'manager.90days': 'Last 90 days',
    'manager.custom': 'Custom',
    'manager.manageTeam': 'Manage Team',
    'manager.viewAllLeads': 'View All Leads',
    'manager.reports': 'Reports',
    'manager.setGoals': 'Set Goals',

    // Sales Dashboard
    'sales.title': 'Sales Dashboard',
    'sales.subtitle': 'Your daily sales activities and leads',
    'sales.myLeads': 'My Leads',
    'sales.activeChats': 'Active Chats',
    'sales.callsMade': 'Calls Made',
    'sales.conversionRate': 'Conversion Rate',
    'sales.urgentLeads': 'Urgent Leads - Action Required',
    'sales.urgentLeadsDesc': 'High priority leads that need immediate attention',
    'sales.recentChats': 'Recent Chats',
    'sales.recentChatsDesc': 'Active conversations',
    'sales.todayTasks': "Today's Tasks",
    'sales.todayTasksDesc': 'Your schedule for today',
    'sales.table.priority': 'Priority',
    'sales.table.lead': 'Lead',
    'sales.table.product': 'Product',
    'sales.table.budget': 'Budget',
    'sales.table.lastContact': 'Last Contact',
    'sales.table.status': 'Status',
    'sales.table.action': 'Action',
    'priority.high': 'High',
    'priority.medium': 'Medium',
    'priority.low': 'Low',
    'sales.makeCall': 'Make Call',
    'sales.sendMessage': 'Send Message',
    'sales.addLead': 'Add Lead',
    'sales.updateStatus': 'Update Status',
    'sales.myStats': 'My Stats',
    'sales.viewAllChats': 'View All Chats',

    // Users Page
    'users.title': 'User Management',
    'users.subtitle': 'Manage user accounts and permissions',
    'users.addUser': 'Add User',
    'users.totalUsers': 'Total Users',
    'users.activeUsers': 'Active Users',
    'users.newThisMonth': 'New This Month',
    'users.role': 'Role',
    'users.lastActive': 'Last Active',
    'users.postsAnalyzed': 'Posts Analyzed',
    'users.viewDetails': 'View Details',

    // Posts Page
    'posts.title': 'Posts Management',
    'posts.subtitle': 'Social media posts collected and analyzed',
    'posts.totalPosts': 'Total Posts',
    'posts.buyingDemand': 'Buying Demand',
    'posts.sellingDemand': 'Selling Demand',
    'posts.filtered': 'Filtered',
    'posts.platform': 'Platform',
    'posts.content': 'Content',
    'posts.sentiment': 'Sentiment',
    'posts.author': 'Author',
    'posts.type': 'Type',
    'posts.buying': 'Buying',
    'posts.selling': 'Selling',
    'posts.spam': 'Spam',
    'posts.positive': 'Positive',
    'posts.neutral': 'Neutral',
    'posts.negative': 'Negative',
    // Posts – extra labels
    'posts.today': 'Today',
    'posts.noPosts': 'No posts',
    'posts.noPostsHint': 'Posts will appear here after scraping from the "Data Scraper" page',
    'posts.refresh': 'Refresh',
    'posts.table.content': 'Content',
    'posts.table.type': 'Type',
    'posts.table.category': 'Category',
    'posts.table.platform': 'Platform',
    'posts.table.author': 'Author',
    'posts.table.price': 'Price',
    'posts.table.confidence': 'Confidence',
    'posts.table.active': 'Active',
    'posts.table.time': 'Time',
    'posts.table.actions': 'Actions',
    'posts.viewOriginal': 'View Original',

    // Products Page
    'products.title': 'Product Management',
    'products.subtitle': 'Track prices and market demand',
    'products.addProduct': 'Add Product',
    'products.addTrackedProduct': 'Add Tracked Product',
    'products.totalProducts': 'Total Products',
    'products.highDemand': 'High Demand',
    'products.totalBuyingPosts': 'Total Buying Posts',
    'products.totalSellingPosts': 'Total Selling Posts',
    'products.avgPrice': 'Avg Price',
    'products.minPrice': 'Min Price',
    'products.maxPrice': 'Max Price',
    'products.priceRange': 'Price Range',
    'products.product': 'Product',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.demand': 'Demand',
    'products.mentions': 'Mentions',
    'products.trend': 'Trend',
    'products.high': 'High',
    'products.medium': 'Medium',
    'products.low': 'Low',
    'products.trending': 'Trending',
    'products.stable': 'Stable',
    'products.declining': 'Declining',
    'products.listTitle': 'Product List',
    'products.searchPlaceholder': 'Search products...',
    'products.editProduct': 'Edit Product',

    // Leads Page
    'leads.title': 'Lead Management',
    'leads.subtitle': 'Track and manage potential customers',
    'leads.addLead': 'Add Lead',
    'leads.totalLeads': 'Total Leads',
    'leads.hot': 'Hot Leads',
    'leads.contacted': 'Contacted',
    'leads.converted': 'Converted',
    'leads.lead': 'Lead',
    'leads.contact': 'Contact',
    'leads.interest': 'Interest',
    'leads.source': 'Source',
    'leads.assignedTo': 'Assigned To',
    'leads.priority': 'Priority',
    'leads.new': 'New',
    'leads.inProgress': 'In Progress',
    'leads.closed': 'Closed',
    // Leads – extra labels
    'leads.highPotential': 'High potential',
    'leads.table.priority': 'Priority',
    'leads.table.lead': 'Lead',
    'leads.table.contact': 'Contact',
    'leads.table.interest': 'Interest',
    'leads.table.type': 'Type',
    'leads.table.budget': 'Budget',
    'leads.table.status': 'Status',
    'leads.table.source': 'Source',
    'leads.table.notes': 'Notes',
    'leads.table.actions': 'Actions',
    'leads.filter.placeholder': 'Search...',
    'leads.status.new': 'New',
    'leads.status.potential': 'Potential',
    'leads.status.ready': 'Ready to buy',
    'leads.status.purchased': 'Purchased',
    'leads.status.contacted': 'Contacted',
    'leads.status.qualified': 'Qualified',
    'leads.status.lost': 'Lost',

    // Sales Log
    'sidebar.salesLog': 'Sales Log',
    'salesLog.title': 'Sales Log',
    'salesLog.subtitle': 'Track customer care history',
    'salesLog.totalLogs': 'Total Logs',
    'salesLog.caretaker': 'Caretaker',
    'salesLog.editTime': 'Edit time',
    'salesLog.customerRequest': 'Customer request',
    'salesLog.conclusion': 'Conclusion',
    'salesLog.adminResponse': 'Admin response',
    'salesLog.pending': 'Pending',
    'salesLog.approved': 'Approved - Sell',
    'salesLog.rejected': 'Rejected - No sell',
    'salesLog.noLogs': 'No logs yet',
    'salesLog.customer': 'Customer',
    'salesLog.approve': 'Approve',
    'salesLog.reject': 'Reject',
    'salesLog.reviewDialogTitle': 'Review Sales Log',
    'salesLog.reviewDialogDesc': 'Confirm approval or rejection of this log',
    'salesLog.approveSuccess': 'Approved successfully',
    'salesLog.rejectSuccess': 'Rejected',
    'salesLog.searchPlaceholder': 'Search...',
    'salesLog.reviewCustomer': 'Customer',
    'salesLog.reviewCaretaker': 'Caretaker',
    'salesLog.reviewRequest': 'Request',
    'salesLog.reviewConclusion': 'Conclusion',
    'salesLog.reviewAdminResponse': 'Admin Response',
    'salesLog.reviewAdminResponsePlaceholder': 'Enter response...',

    // Conversations Page
    'conversations.title': 'Conversations',
    'conversations.subtitle': 'Manage messages and customer interactions',
    'conversations.totalChats': 'Total Chats',
    'conversations.unread': 'Unread',
    'conversations.avgResponse': 'Avg Response',
    'conversations.satisfaction': 'Satisfaction',
    'conversations.selectChat': 'Select a chat to view details',
    'conversations.typeMessage': 'Type a message...',
    'conversations.send': 'Send',

    // Reports Page
    'reports.title': 'Reports & Analytics',
    'reports.subtitle': 'Performance overview and trends',
    'reports.generateReport': 'Generate Report',
    'reports.totalRevenue': 'Total Revenue',
    'reports.newLeads': 'New Leads',
    'reports.conversionRate': 'Conversion Rate',
    'reports.customerSatisfaction': 'Customer Satisfaction',
    'reports.performanceOverview': 'Performance Overview',
    'reports.topProducts': 'Top Products',
    // Reports – UI texts
    'reports.totalPosts': 'Total posts',
    'reports.buyingPosts': 'Buying posts',
    'reports.sellingPosts': 'Selling posts',
    'reports.avgConfidence': 'Avg confidence',
    'reports.categoryDistributionTitle': 'Distribution by category',
    'reports.categoryDistributionDesc': 'Top product categories of interest',
    'reports.locationDistributionTitle': 'Distribution by location',
    'reports.locationDistributionDesc': 'Locations with highest demand',
    'reports.avgPriceTrendTitle': 'Average price trend',
    'reports.buySellRatioTitle': 'Buy/Sell ratio',
    'reports.avgResponseTimeTitle': 'Average response time',
    'reports.range7days': 'Last 7 days',
    'reports.range30days': 'Last 30 days',
    'reports.range90days': 'Last 90 days',
    'reports.rangeCustom': 'Custom',
    'reports.pickDate': 'Pick date',
    'reports.exportFormatExcel': 'Excel',
    'reports.exportFormatCsv': 'CSV',
    'reports.exportButton': 'Export report',
    'reports.exportSuccess': 'Report exported successfully',
    'reports.exportError': 'Failed to export report',

    // AI Settings Page
    'ai.title': 'AI System Settings',
    'ai.subtitle': 'Configure and manage AI models',
    'ai.models': 'AI Models',
    'ai.nlpModel': 'NLP Model',
    'ai.ocrModel': 'OCR Model',
    'ai.spamDetector': 'Spam Detector',
    'ai.priceExtractor': 'Price Extractor',
    'ai.confidence': 'Confidence',
    'ai.accuracy': 'Accuracy',
    'ai.performance': 'Performance',
    'ai.configure': 'Configure',
    'ai.retrain': 'Retrain',

    // Sources Page
    'sources.title': 'Data Sources',
    'sources.subtitle': 'Manage social media connections and data collection',
    'sources.addSource': 'Add New Source',
    'sources.source': 'Source',
    'sources.connected': 'Connected',
    'sources.postsCollected': 'Posts Collected',
    'sources.lastSync': 'Last Sync',
    'sources.syncNow': 'Sync Now',
    'sources.disconnect': 'Disconnect',

    // Groups Page
    'groups.title': 'Facebook Groups',
    'groups.subtitle': 'List of scraped groups and manually added groups',
    'groups.totalGroups': 'Total groups',
    'groups.searchPlaceholder': 'Search by name, URL or location...',
    'groups.name': 'Group name',
    'groups.url': 'Group URL',
    'groups.location': 'Location',
    'groups.keywords': 'Keywords',
    'groups.addGroup': 'Add group manually',
    'groups.fetchName': 'Fetch group name automatically',
    'groups.deleteConfirm': 'Are you sure you want to delete this group?',

    // Scraper Page
    'scraper.subtitle': 'Collect data from Facebook Groups and Marketplace',
    'scraper.step1Title': 'Step 1: Login to Facebook',
    'scraper.step1Desc': 'Login to save cookies and use them for scraping',
    'scraper.emailLabel': 'Facebook Email',
    'scraper.loginButton': 'Login & Save Cookie',
    'scraper.modeTitle': 'Select scraping mode',
    'scraper.searchModeTitle': 'Search Mode',
    'scraper.searchModeDesc': 'Search by keywords',
    'scraper.feedModeTitle': 'Feed Mode',
    'scraper.feedModeDesc': 'Scroll feed & filter',
    'scraper.step2SearchTitle': 'Step 2: Search scraping',
    'scraper.step2SearchDesc': 'Enter Group/Marketplace link and keywords to search',
    'scraper.groupLinkLabel': 'Group or Marketplace link',
    'scraper.keywordsLabel': 'Keywords (one per line)',
    'scraper.searchButtonIdle': '🔍 Run Search',
    'scraper.searchButtonLoading': 'Searching...',
    'scraper.step2FeedTitle': 'Step 2: Feed scraping',
    'scraper.step2FeedDesc': 'Open feed and scroll to load posts, AI will classify automatically',
    'scraper.feedLinkLabel': 'Feed link',
    'scraper.newsfeedButton': '🏠 Newsfeed',
    'scraper.allGroupsButton': '👥 All Groups',
    'scraper.scrollLabel': 'Scroll count',
    'scraper.scrollMin': '5 (Fast)',
    'scraper.scrollMax': '30 (Many)',
    'scraper.feedButtonIdle': '🚀 Run Feed scraping',
    'scraper.feedButtonLoading': 'Scraping feed...',
    'scraper.serverOnline': 'Server Online',
    'scraper.serverOffline': 'Server Offline',
    'scraper.serverChecking': 'Checking...',
    'scraper.offlineTitle': 'Backend server is not running',
    'scraper.offlineDesc': 'Start the backend server before using this feature:',

    // Research Page
    'research.title': 'Market Research',
    'research.subtitle': 'Analyze market trends and insights',
    'research.startResearch': 'Start Research',
    'research.marketTrends': 'Market Trends',
    'research.keywords': 'Keywords',
    'research.insights': 'Insights',

    // Roles
    'role.admin': 'Administrator',
    'role.manager': 'Store Manager',
    'role.sales': 'Sales Staff',
    'role.smb': 'SMB Owner',
    'role.student': 'IT Student',

    // Account
    'account.button': 'Account',
    'account.title': 'Account Management',
    'account.subtitle': 'View and edit your account information',
    'account.profileTab': 'Profile',
    'account.passwordTab': 'Change Password',
    'account.createdAt': 'Created',
    'account.unknown': 'Unknown',
    'account.enterName': 'Enter your full name',
    'account.emailCannotChange': 'Email cannot be changed',
    'account.currentPassword': 'Current Password',
    'account.newPassword': 'New Password',
    'account.enterCurrentPassword': 'Enter current password',
    'account.enterNewPassword': 'Enter new password',
    'account.confirmNewPassword': 'Confirm new password',
    'account.changePassword': 'Change Password',
    'account.saving': 'Saving...',
    'account.updateSuccess': 'Profile updated successfully',
    'account.updateFailed': 'Failed to update profile',
    'account.changePasswordSuccess': 'Password changed successfully',
    'account.changePasswordFailed': 'Failed to change password',
    'account.fillAllFields': 'Please fill in all fields',
    'account.passwordMismatch': 'Passwords do not match',
    'account.passwordTooShort': 'Password must be at least 6 characters',
    'account.enterPhone': 'Enter phone number',
    'account.company': 'Company / Organization',
    'account.enterCompany': 'Enter company or organization name',
    'account.location': 'Address',
    'account.enterLocation': 'Enter your address',

    // Login Page
    'login.welcomeBack': 'Welcome back!',
    'login.systemDesc': 'AI system for analyzing buy/sell demand on social media',
    'login.aiAnalysis': 'Smart AI Analysis',
    'login.aiAccuracy': 'Up to 94.2% accuracy',
    'login.autoCollect': 'Automatic data collection',
    'login.platformList': 'From Facebook, Instagram, Twitter',
    'login.detailedReports': 'Detailed reports',
    'login.marketTrends': 'Market trend analysis',
    'login.title': 'Login',
    'login.subtitle': 'Enter your credentials to continue',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loggingIn': 'Logging in...',
    'login.loginButton': 'Login',
    'login.orDemoAccount': 'Or use demo account',
    'login.noAccount': "Don't have an account?",
    'login.registerNow': 'Register now',
    'login.forgotTitle': 'Forgot Password',
    'login.forgotDesc': 'Enter your email to receive a verification code (OTP) to reset your password.',
    'login.enterEmail': 'Please enter email',
    'login.sendingCode': 'Sending verification code...',
    'login.codeSent': 'If the email exists, a verification code has been sent. Please check your inbox.',
    'login.errorSendCode': 'Error sending verification code',
    'login.cancel': 'Cancel',
    'login.sendCode': 'Send code',
    'login.sending': 'Sending...',
    'login.step2Desc': 'Enter the verification code sent to your email and set a new password.',
    'login.otpLabel': 'Verification Code (OTP)',
    'login.otpPlaceholder': 'Enter 6-digit code',
    'login.newPassword': 'New Password',
    'login.confirmNewPassword': 'Confirm New Password',
    'login.back': 'Back',
    'login.resendCode': 'Resend code',
    'login.resendingCode': 'Resending verification code...',
    'login.codeResent': 'If the email exists, a new verification code has been sent. Please check your inbox.',
    'login.errorResendCode': 'Error resending verification code',
    'login.fillAllFields': 'Please fill in all fields',
    'login.changingPassword': 'Changing password...',
    'login.changePassword': 'Change Password',
    'login.passwordChanged': 'Password changed successfully',
    'login.passwordChangeFailed': 'Failed to change password',
    'login.processing': 'Processing...',
    'login.enterEmailFirst': 'Please enter email to resend code',

    // Register Page
    'register.startFree': 'Start free today',
    'register.createDesc': 'Create an account and experience the power of AI in social media analysis',
    'register.freeTrial': '30-day free trial',
    'register.noCard': 'No credit card required',
    'register.setup5min': 'Setup in 5 minutes',
    'register.easyFast': 'Easy and fast',
    'register.support247': '24/7 Support',
    'register.supportDesc': 'Our support team is always ready',
    'register.haveAccount': 'Already have an account?',
    'register.loginNow': 'Login now',
    'register.createAccount': 'Create Account',
    'register.fillInfo': 'Fill in your information to get started',
    'register.fullName': 'Full Name',
    'register.namePlaceholder': 'John Doe',
    'register.phone': 'Phone Number',
    'register.phonePlaceholder': '0912345678',
    'register.phoneAvailable': 'Phone number is available',
    'register.phoneTaken': 'This phone number is already registered',
    'register.emailAvailable': 'Email is available',
    'register.emailTaken': 'This email is already registered',
    'register.otpLabel': 'Verification Code',
    'register.otpPlaceholder': 'Enter 6-digit code sent to email',
    'register.sendOtp': 'Send code',
    'register.sendingOtp': 'Sending...',
    'register.otpSending': 'Sending verification code...',
    'register.otpSent': 'Verification code has been sent. Please check your inbox (including Spam folder).',
    'register.otpError': 'Failed to send verification code. Please try again.',
    'register.enterEmailFirst': 'Please enter email before sending code',
    'register.company': 'Company',
    'register.companyPlaceholder': 'Company name',
    'register.location': 'Location',
    'register.locationPlaceholder': 'Ha Noi',
    'register.role': 'Role',
    'register.rolePlaceholder': 'Select your role',
    'register.roleSMB': 'SMB Owner - Small Business Owner',
    'register.roleSales': 'Sales Staff',
    'register.roleManager': 'Store Manager',
    'register.roleStudent': 'IT Student',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.agreeTerms': 'I agree to the',
    'register.termsOfUse': 'Terms of Use',
    'register.and': 'and',
    'register.privacyPolicy': 'Privacy Policy',
    'register.createButton': 'Create Account',
    'register.consentText': 'By registering, you agree to receive emails about products, updates and promotions.',
    'register.validation.fullName': 'Please enter your full name',
    'register.validation.email': 'Please enter email',
    'register.validation.emailInvalid': 'Invalid email format',
    'register.validation.phone': 'Please enter phone number',
    'register.validation.phoneInvalid': 'Invalid phone number',
    'register.validation.role': 'Please select a role',
    'register.validation.password': 'Please enter password',
    'register.validation.passwordMin': 'Password must be at least 6 characters',
    'register.validation.passwordMismatch': 'Passwords do not match',
    'register.validation.otp': 'Please enter the verification code sent to email',
    'register.validation.terms': 'Please agree to the terms',

    // AI Settings Page
    'aiSettings.title': 'AI Settings',
    'aiSettings.subtitle': 'Configure AI models and analysis parameters',
    'aiSettings.modelConfig': 'AI Model Configuration',
    'aiSettings.modelConfigDesc': 'Manage AI modules and their settings',
    'aiSettings.nlpModel': 'NLP Text Classifier',
    'aiSettings.nlpDesc': 'Classifies posts as buying or selling requests',
    'aiSettings.ocrModel': 'OCR Image Reader',
    'aiSettings.ocrDesc': 'Extracts text from images in posts',
    'aiSettings.spamDetector': 'Spam Detector',
    'aiSettings.spamDesc': 'Filters out spam and fraudulent posts',
    'aiSettings.priceExtractor': 'Price Extractor',
    'aiSettings.priceDesc': 'Identifies and extracts price information',
    'aiSettings.accuracy': 'Accuracy',
    'aiSettings.advancedSettings': 'Advanced Settings',
    'aiSettings.advancedDesc': 'Fine-tune AI analysis parameters',
    'aiSettings.confidenceThreshold': 'Confidence Threshold',
    'aiSettings.confidenceHint': 'Only show results with confidence level above this threshold',
    'aiSettings.modelVersion': 'Model Version',
    'aiSettings.versionStable': 'Stable',
    'aiSettings.versionProduction': 'Production',
    'aiSettings.versionLatest': 'Latest',
    'aiSettings.versionBeta': 'Beta',
    'aiSettings.versionHint': 'Select the AI model version to use for analysis',
    'aiSettings.saveConfig': 'Save Configuration',
    'aiSettings.resetDefault': 'Reset to Default',
    'aiSettings.performance': 'Model Performance',
    'aiSettings.performanceDesc': 'Real-time performance metrics',
    'aiSettings.overallAccuracy': 'Overall Accuracy',
    'aiSettings.processingSpeed': 'Processing Speed',
    'aiSettings.avgPerPost': 'avg. per post',
    'aiSettings.activeModels': 'Active Models',
    'aiSettings.quickActions': 'Quick Actions',
    'aiSettings.testModel': 'Test Model',
    'aiSettings.calibrate': 'Calibrate Models',
    'aiSettings.viewTrainingData': 'View Training Data',

    // Scraper Page - Additional
    'scraper.enterFbEmail': 'Please enter Facebook email',
    'scraper.openingChrome': 'Opening Chrome for login...',
    'scraper.loginSuccess': 'Login successful!',
    'scraper.loginError': 'Login error',
    'scraper.cannotConnectScraper': 'Cannot connect to scraper server',
    'scraper.checkServer': 'Please check if server is running.',
    'scraper.fillAllInfo': 'Please fill in all information',
    'scraper.scrapingAI': 'Scraping data and analyzing with AI...',
    'scraper.foundPosts': 'Found {count} posts!',
    'scraper.savedInfo': 'Saved: {posts} posts, {leads} leads',
    'scraper.errorScraping': 'Error scraping data',
    'scraper.cannotConnect': 'Cannot connect to server',
    'scraper.enterEmailKeywords': 'Please enter email and keywords',
    'scraper.scanningGroups': 'Scanning groups related to keywords...',
    'scraper.foundGroups': 'Found {count} groups related to keywords',
    'scraper.errorGroups': 'Error scanning groups',
    'scraper.cannotConnectGroups': 'Cannot connect to server (group scanning)',
    'scraper.fillEmailFeed': 'Please fill in all information (email and feed link)',
    'scraper.scrapingFeeds': 'Scraping {count} feeds with {priority} priority...',
    'scraper.priorityHigh': 'High',
    'scraper.priorityMedium': 'Medium',
    'scraper.priorityLow': 'Low',
    'scraper.foundPostsFromGroups': 'Found {posts} posts from {groups} groups!',
    'scraper.location': 'Location (optional)',
    'scraper.locationPlaceholder': 'e.g. Ha Noi, Ho Chi Minh, Da Nang...',
    'scraper.locationHint': 'If you enter a location, the system will prioritize finding groups related to that area.',
    'scraper.scanning': 'Scanning...',
    'scraper.scanGroupsBtn': 'Scan groups by keywords',
    'scraper.feedLabel': 'Facebook group link (or select from scraped list)',
    'scraper.feedPlaceholder': 'https://www.facebook.com/groups/123456789\n(One link per line)',
    'scraper.selectFromScraped': 'Select from scraped groups',
    'scraper.clear': 'Clear',
    'scraper.selectedGroups': 'Selected {count} groups',
    'scraper.priorityLabel': 'Scraping priority level',
    'scraper.priorityHighDesc': 'High - Thorough scan, more posts',
    'scraper.priorityMediumDesc': 'Medium - Balanced',
    'scraper.priorityLowDesc': 'Low - Fast, fewer posts',
    'scraper.enterLinkWarning': 'Please enter group link or select from scraped list',
    'scraper.groupListTitle': 'Groups related to keywords',
    'scraper.keywords': 'Keywords',
    'scraper.openGroup': 'Open group',
    'scraper.results': 'Results',
    'scraper.autoSaved': 'auto-saved',
    'scraper.buy': 'Buy',
    'scraper.sell': 'Sell',
    'scraper.other': 'Other',
    'scraper.confidence': 'confidence',

    // Sales Dashboard
    'sales.title': 'Sales Dashboard',
    'sales.subtitle': 'Manage your leads and sales activities',
    'sales.myLeads': 'My Leads',
    'sales.activeChats': 'Active Chats',
    'sales.callsMade': 'Calls Made',
    'sales.conversionRate': 'Conversion Rate',
    'sales.viewAllChats': 'View All Chats',
    'sales.urgentLeads': 'Urgent Leads',
    'sales.urgentLeadsDesc': 'High priority potential customers',
    'sales.recentChats': 'Recent Chats',
    'sales.recentChatsDesc': 'Latest conversations',
    'sales.todayTasks': 'Today Tasks',
    'sales.todayTasksDesc': 'Your work schedule',
    'sales.makeCall': 'Make Call',
    'sales.sendMessage': 'Send Message',
    'sales.addLead': 'Add Lead',
    'sales.updateStatus': 'Update',
    'sales.myStats': 'My Stats',
    'sales.table.priority': 'Priority',
    'sales.table.lead': 'Lead',
    'sales.table.product': 'Product',
    'sales.table.budget': 'Budget',
    'sales.table.lastContact': 'Last Contact',
    'sales.table.status': 'Status',
    'sales.table.action': 'Action',
    'sales.today': 'today',
    'sales.unread': 'unread',

    // Priority
    'priority.high': 'High',
    'priority.medium': 'Medium',
    'priority.low': 'Low',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Khởi tạo ngôn ngữ từ localStorage hoặc mặc định là 'vi'
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('aifilter.language');
      if (saved === 'en' || saved === 'vi') return saved;
    } catch {
      // ignore
    }
    return 'vi';
  });

  // Wrapper để lưu vào localStorage khi thay đổi ngôn ngữ
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('aifilter.language', lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['vi']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}